from __future__ import annotations

MEDICAL_DISCLAIMER = (
    "This assistant provides educational guidance only and is not a medical diagnosis. "
    "Seek a licensed clinician or emergency care for severe, worsening, or concerning symptoms."
)

UNCERTAIN_CONDITION = "Unclear Pattern / Needs Clinical Evaluation"

SYMPTOM_SYNONYMS = {
    "fever": ["fever", "high temperature", "temperature", "feverish"],
    "cough": ["cough", "dry cough", "wet cough", "persistent cough"],
    "sore throat": ["sore throat", "throat pain", "scratchy throat"],
    "runny nose": ["runny nose", "nasal discharge", "dripping nose"],
    "sneezing": ["sneezing", "sneeze", "sneezes"],
    "fatigue": ["fatigue", "tiredness", "exhaustion", "low energy"],
    "headache": ["headache", "head pain", "migraine"],
    "body ache": ["body ache", "muscle ache", "body pain", "joint pain"],
    "chest pain": ["chest pain", "chest tightness", "pressure in chest"],
    "shortness of breath": [
        "shortness of breath",
        "breathing trouble",
        "difficulty breathing",
        "breathless",
    ],
    "wheezing": ["wheezing", "whistling breath"],
    "nausea": ["nausea", "queasy"],
    "vomiting": ["vomiting", "throwing up", "vomit"],
    "diarrhea": ["diarrhea", "loose stools", "watery stool"],
    "abdominal pain": ["abdominal pain", "stomach pain", "belly pain", "cramps"],
    "left upper abdominal pain": [
        "left upper abdominal pain",
        "left upper belly pain",
        "left upper quadrant pain",
        "pain under left ribs",
        "pain near spleen",
        "pain around spleen",
        "spleen pain",
        "pain behind spleen",
        "pain in the back of the spleen",
        "pain in back of the spleen",
        "pain in spleen area",
    ],
    "right lower abdominal pain": [
        "right lower abdominal pain",
        "right lower belly pain",
        "right lower quadrant pain",
        "pain in lower right abdomen",
        "pain on lower right side of abdomen",
        "pain near appendix",
        "appendix pain",
    ],
    "loss of taste": ["loss of taste", "can't taste", "reduced taste"],
    "loss of smell": ["loss of smell", "can't smell", "reduced smell"],
    "rash": ["rash", "skin rash", "red spots"],
    "dehydration": ["dehydration", "very thirsty", "dry mouth"],
    "burning urination": [
        "burning urination",
        "pain while urinating",
        "pain while peeing",
        "burning while peeing",
        "peeing hurts",
        "urine burns",
    ],
    "frequent urination": ["frequent urination", "urinating often", "pee often"],
    "blood in urine": [
        "blood in urine",
        "blood in my urine",
        "bloody urine",
        "urine is bloody",
        "red urine",
        "pink urine",
        "urine has blood",
        "my urine has blood",
    ],
    "high blood sugar": [
        "high blood sugar",
        "blood sugar is high",
        "blood sugar high",
        "blood sugar level is high",
        "high sugar level",
        "elevated blood sugar",
        "high glucose",
        "glucose is high",
        "hyperglycemia",
    ],
    "excessive thirst": [
        "excessive thirst",
        "very thirsty",
        "thirsty all the time",
        "always thirsty",
    ],
    "blurred vision": [
        "blurred vision",
        "blurry vision",
        "vision is blurry",
        "can't see clearly",
    ],
    "increased hunger": ["increased hunger", "hungry all the time", "always hungry"],
    "weight loss": ["weight loss", "losing weight", "unexplained weight loss"],
    "back pain": [
        "back pain",
        "backache",
        "lower back pain",
        "upper back pain",
        "mid back pain",
        "pain in my back",
        "pain in lower back",
        "flank pain",
        "side pain",
        "side discomfort",
        "sharp side pain",
    ],
    "facial pain": ["facial pain", "sinus pain", "face pain", "sinus pressure", "pressure around cheeks"],
    "ear pain": ["ear pain", "earache", "pain in ear"],
    "heartburn": ["heartburn", "acid reflux", "burning in chest after eating", "acidity"],
    "bloating": ["bloating", "bloated", "stomach feels full"],
    "appetite loss": ["appetite loss", "loss of appetite", "not feeling hungry"],
    "swollen glands": ["swollen glands", "swollen lymph nodes", "neck glands swollen"],
    "stiffness": ["stiffness", "back stiffness", "muscle stiffness", "stiff back"],
    "sensitivity to light": ["sensitivity to light", "light hurts", "photophobia"],
    "dizziness": ["dizziness", "lightheaded", "vertigo"],
    "itchy eyes": ["itchy eyes", "eye itching", "watery itchy eyes"],
    "congestion": ["congestion", "blocked nose", "stuffy nose"],
    "chills": ["chills", "shivering"],
}

EMERGENCY_SYMPTOMS = {
    "chest pain",
    "shortness of breath",
}

MEDIUM_RISK_SYMPTOMS = {
    "persistent fever",
    "dehydration",
    "vomiting",
    "diarrhea",
    "burning urination",
    "back pain",
    "left upper abdominal pain",
    "right lower abdominal pain",
    "blood in urine",
    "rash",
}

URGENT_PHRASES = [
    "cannot breathe",
    "can't breathe",
    "hard to breathe",
    "severe chest pain",
    "confused",
    "fainted",
    "passing out",
    "fruity breath",
    "very drowsy",
]

DISEASE_PROFILES = {
    "Common Cold": {
        "hallmark_symptoms": ["runny nose", "sneezing", "sore throat", "cough"],
        "description": "A mild upper respiratory infection that often improves with rest and fluids.",
        "self_care": [
            "Rest and stay hydrated.",
            "Use warm fluids and saline nasal rinses for comfort.",
            "Monitor for worsening fever or breathing difficulty.",
        ],
        "escalation": "Seek clinical advice if symptoms last more than a week or breathing becomes difficult.",
        "doc_tags": ["common_cold", "respiratory_care"],
    },
    "Influenza": {
        "hallmark_symptoms": ["fever", "cough", "fatigue", "body ache", "headache", "chills"],
        "description": "An acute viral illness that can cause sudden fever, body aches, and fatigue.",
        "self_care": [
            "Rest, fluids, and fever monitoring are important.",
            "Avoid spreading infection by limiting close contact.",
            "Get evaluated sooner if symptoms are severe or you are medically vulnerable.",
        ],
        "escalation": "Worsening breathing, dehydration, or fever lasting several days needs clinician review.",
        "doc_tags": ["influenza", "fever_guidance"],
    },
    "COVID-19": {
        "hallmark_symptoms": [
            "fever",
            "cough",
            "fatigue",
            "loss of taste",
            "loss of smell",
            "shortness of breath",
        ],
        "description": "A viral respiratory infection with a wide range of severity and symptom combinations.",
        "self_care": [
            "Reduce contact with others and monitor oxygen-related symptoms closely.",
            "Stay hydrated and rest.",
            "Use local testing or clinician guidance when available.",
        ],
        "escalation": "Urgent evaluation is needed for breathing difficulty, chest pain, or confusion.",
        "doc_tags": ["covid19", "respiratory_care"],
    },
    "Gastroenteritis": {
        "hallmark_symptoms": ["nausea", "vomiting", "diarrhea", "abdominal pain", "dehydration"],
        "description": "An intestinal illness commonly associated with vomiting, loose stools, and stomach cramps.",
        "self_care": [
            "Focus on oral hydration with small frequent sips.",
            "Avoid greasy foods until symptoms settle.",
            "Watch for dehydration or inability to keep fluids down.",
        ],
        "escalation": "Persistent vomiting, blood in stool, or dehydration should be assessed promptly.",
        "doc_tags": ["gastroenteritis", "hydration"],
    },
    "Migraine": {
        "hallmark_symptoms": ["headache", "nausea", "sensitivity to light", "dizziness"],
        "description": "A recurrent headache disorder that can include nausea and sensitivity to light.",
        "self_care": [
            "Rest in a quiet, dark room.",
            "Maintain hydration and identify triggers.",
            "Seek care if the headache is sudden, severe, or neurologically unusual.",
        ],
        "escalation": "Sudden severe headache, confusion, or weakness needs urgent evaluation.",
        "doc_tags": ["migraine", "headache_care"],
    },
    "Allergic Rhinitis": {
        "hallmark_symptoms": ["sneezing", "runny nose", "congestion", "itchy eyes"],
        "description": "An allergy-related nasal condition that causes sneezing, congestion, and itchy eyes.",
        "self_care": [
            "Reduce exposure to known allergens where possible.",
            "Use hydration and avoid irritants like smoke.",
            "Track whether symptoms follow dust or pollen exposure.",
        ],
        "escalation": "Breathing issues or wheezing should be assessed by a clinician.",
        "doc_tags": ["allergic_rhinitis", "allergy_control"],
    },
    "Bronchitis": {
        "hallmark_symptoms": ["cough", "fatigue", "wheezing", "chest pain", "fever"],
        "description": "An airway inflammation pattern often associated with cough and sometimes wheezing.",
        "self_care": [
            "Rest, hydration, and smoke avoidance can help.",
            "Monitor the intensity of cough and breathing effort.",
            "Escalate if wheezing or chest discomfort worsens.",
        ],
        "escalation": "Shortness of breath, chest pain, or persistent fever needs prompt care.",
        "doc_tags": ["bronchitis", "respiratory_care"],
    },
    "Urinary Tract Infection": {
        "hallmark_symptoms": ["burning urination", "frequent urination", "fever", "back pain"],
        "description": "A urinary infection pattern that often causes burning and frequent urination.",
        "self_care": [
            "Increase fluid intake unless restricted by a clinician.",
            "Track fever, back pain, or worsening discomfort.",
            "Prompt treatment may be needed to avoid kidney involvement.",
        ],
        "escalation": "Fever with back pain suggests a more urgent need for clinician evaluation.",
        "doc_tags": ["uti", "hydration"],
    },
    "Sinusitis": {
        "hallmark_symptoms": ["congestion", "runny nose", "headache", "facial pain", "sore throat"],
        "description": "An upper-airway inflammation pattern with congestion, facial pressure, and headache.",
        "self_care": [
            "Hydrate and consider steam or saline rinses for nasal comfort.",
            "Track facial pressure, fever, and worsening headache.",
            "Seek review if symptoms are persistent or severe.",
        ],
        "escalation": "High fever, eye swelling, severe headache, or confusion needs urgent evaluation.",
        "doc_tags": ["sinusitis", "respiratory_care"],
    },
    "Asthma Exacerbation": {
        "hallmark_symptoms": ["shortness of breath", "wheezing", "cough", "chest pain", "fatigue"],
        "description": "An airway tightening pattern that can cause wheeze, breathlessness, and cough.",
        "self_care": [
            "Use your prescribed reliever treatment plan if you have one.",
            "Avoid smoke and known triggers.",
            "Monitor breathing effort closely.",
        ],
        "escalation": "Worsening breathlessness, chest tightness, or difficulty speaking requires urgent care.",
        "doc_tags": ["asthma", "respiratory_care"],
    },
    "Kidney Stone / Renal Colic": {
        "hallmark_symptoms": ["back pain", "blood in urine", "nausea", "vomiting", "burning urination"],
        "description": "A urinary stone pattern that often causes flank or back pain with nausea or blood in urine.",
        "self_care": [
            "Hydrate unless a clinician has told you otherwise.",
            "Track urine color, pain severity, and vomiting.",
            "Arrange clinical review if symptoms persist or intensify.",
        ],
        "escalation": "Severe pain, fever, inability to pass urine, or persistent vomiting needs urgent assessment.",
        "doc_tags": ["kidney_stone", "hydration"],
    },
    "Gastritis / Acid Peptic Disorder": {
        "hallmark_symptoms": ["abdominal pain", "nausea", "heartburn", "bloating", "appetite loss"],
        "description": "An upper-digestive irritation pattern with stomach discomfort, nausea, or heartburn.",
        "self_care": [
            "Avoid irritant foods, alcohol, and unnecessary pain medicines.",
            "Use small bland meals and hydration.",
            "Monitor whether pain is worsening or linked to vomiting.",
        ],
        "escalation": "Vomiting blood, black stools, or severe abdominal pain needs urgent care.",
        "doc_tags": ["gastritis", "abdominal_pain_general"],
    },
    "Appendicitis Concern": {
        "hallmark_symptoms": ["right lower abdominal pain", "abdominal pain", "nausea", "vomiting", "fever", "appetite loss"],
        "description": "A right-lower-abdominal pain pattern that can require urgent surgical evaluation.",
        "self_care": [
            "Do not delay in-person assessment if right-lower-abdominal pain is increasing.",
            "Avoid heavy meals while awaiting evaluation.",
            "Track fever, vomiting, and worsening tenderness.",
        ],
        "escalation": "Increasing right-lower-abdominal pain, fever, vomiting, or rebound tenderness needs urgent evaluation.",
        "doc_tags": ["appendicitis", "abdominal_pain_general"],
    },
    "Ear Infection": {
        "hallmark_symptoms": ["ear pain", "fever", "sore throat", "headache"],
        "description": "An ear inflammation or infection pattern often associated with localized ear pain and fever.",
        "self_care": [
            "Track fever, worsening pain, or reduced hearing.",
            "Rest and stay hydrated.",
            "Arrange clinician review if symptoms persist or intensify.",
        ],
        "escalation": "Severe ear pain, swelling around the ear, or high fever needs prompt review.",
        "doc_tags": ["ear_infection", "fever_guidance"],
    },
    "Mononucleosis-like Illness": {
        "hallmark_symptoms": ["sore throat", "fever", "fatigue", "headache", "swollen glands"],
        "description": "A prolonged viral throat-and-fatigue pattern that can cause sore throat and swollen glands.",
        "self_care": [
            "Rest and pace activity while fatigue is significant.",
            "Hydrate and monitor throat swelling.",
            "Seek review if symptoms are prolonged or worsening.",
        ],
        "escalation": "Trouble swallowing, breathing issues, or severe abdominal pain needs urgent assessment.",
        "doc_tags": ["mono_like", "fever_guidance"],
    },
    "Musculoskeletal Back Strain": {
        "hallmark_symptoms": ["back pain", "body ache", "fatigue", "stiffness"],
        "description": "A muscle or posture-related back pain pattern without clear infection or urinary features.",
        "self_care": [
            "Reduce strain, use gentle movement, and monitor pain severity.",
            "Note whether pain follows lifting, posture, or exertion.",
            "Seek review if weakness, numbness, or fever appears.",
        ],
        "escalation": "Back pain with weakness, numbness, trauma, or fever requires prompt assessment.",
        "doc_tags": ["musculoskeletal_back", "clinical_evaluation"],
    },
    UNCERTAIN_CONDITION: {
        "hallmark_symptoms": [],
        "description": "The current symptom wording does not map safely to a single supported disease pattern in this assistant.",
        "self_care": [
            "Monitor the exact location, severity, and triggers of the symptom.",
            "Seek a clinician review for persistent or unexplained regional pain.",
            "Do not rely on this assistant alone when the symptom location is unusual or difficult to describe.",
        ],
        "escalation": "Urgent assessment is needed for severe pain, fever, vomiting, fainting, breathing difficulty, chest pain, trauma, or rapidly worsening symptoms.",
        "doc_tags": ["clinical_evaluation", "abdominal_pain_general"],
    },
    "Hyperglycemia / Diabetes Concern": {
        "hallmark_symptoms": [
            "high blood sugar",
            "frequent urination",
            "excessive thirst",
            "fatigue",
            "blurred vision",
            "increased hunger",
            "weight loss",
        ],
        "description": "A glucose-regulation concern that can present with increased urination, thirst, fatigue, and blurred vision.",
        "self_care": [
            "Check blood sugar using your usual home monitoring plan if available.",
            "Stay hydrated and avoid sugary drinks while symptoms are being evaluated.",
            "Arrange clinician follow-up, especially if readings stay high or symptoms are new.",
        ],
        "escalation": "Urgent assessment is needed for vomiting, confusion, deep rapid breathing, fruity breath, or severe weakness.",
        "doc_tags": ["glycemic_control", "metabolic_health"],
    },
    "Dengue-like Viral Fever": {
        "hallmark_symptoms": ["fever", "headache", "body ache", "rash", "nausea"],
        "description": "A mosquito-borne viral fever pattern with fever, body pain, and sometimes rash.",
        "self_care": [
            "Maintain hydration and monitor for bleeding or persistent vomiting.",
            "Rest and avoid dehydration.",
            "Use local public health guidance in endemic areas.",
        ],
        "escalation": "Bleeding, severe abdominal pain, or persistent vomiting needs urgent medical attention.",
        "doc_tags": ["dengue_like", "fever_guidance"],
    },
    "Pneumonia": {
        "hallmark_symptoms": ["fever", "cough", "shortness of breath", "chest pain", "fatigue"],
        "description": "A lung infection pattern that can cause fever, cough, and breathing difficulty.",
        "self_care": [
            "Clinical review is usually important, especially when breathing is affected.",
            "Monitor fever and breathing effort closely.",
            "Do not delay care if symptoms are worsening.",
        ],
        "escalation": "Breathing difficulty, chest pain, or confusion is high risk and needs urgent care.",
        "doc_tags": ["pneumonia", "respiratory_care"],
    },
}

GENERIC_PREVENTION_GUIDANCE = [
    "Keep hydrated and note symptom changes over time.",
    "Track any measurable changes such as temperature, urine frequency, breathing effort, or blood sugar readings.",
    "Seek clinical care sooner if symptoms are getting worse rather than better.",
]
